### PR TITLE
Magic bot 36c3c8115b

### PR DESCRIPTION
**Pull request by phillem15**
**Are you a current Fivetran customer?** 

Evan Phillips, Lead BI Architect, Nordic Global

**What change(s) does this PR introduce?** 

Adding pass through columns for Subsidiaries and Consolidated Exchange Rates staging models.

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x ] No  (please provide explanation how the change is non breaking below.)

**Is this PR in response to a previously created Issue**

- [ ] Yes, Issue [link issue number here]
- [x ] No 

**How did you test the PR changes?** 

 
- [ ] CircleCi  
- [x ] Other (please provide additional testing details below)

Followed the suggested approach in [this post](https://discourse.getdbt.com/t/contributing-to-an-external-dbt-package/657), forked and cloned the repository to my local machine, changed the code and made sure my project ran with the updated code!

**Select which warehouse(s) were used to test the PR**
 
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [x ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:sunglasses:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by fivetran-joemarkiewicz — CHANGES_REQUESTED** [review]
Hi @phillem15 thanks so much for opening this PR! The code changes you applied make sense and I appreciate you leveraging a past PR to guide you in this suggestion 😄 I have one quick question about your changes and two small requests for updates.

- One quick question - do you intend for any of these passthrough fields to be included in any end models within the dbt_netsuite package? Or are you looking to just leverage these fields in the staging models?

- [ ] Can you update the [README](https://github.com/fivetran/dbt_netsuite_source#passthrough-columns) section on describing the passthrough columns to include the two additional variables you are adding in this PR
- [ ] Can you make a small update in the [CHANGELOG](https://github.com/fivetran/dbt_netsuite_source/blob/main/CHANGELOG.md) to detail your update. Be sure to add yourself in the next release contributors section!

**Comment by phillem15** [comment]
Hi @fivetran-joemarkiewicz thanks for reaching out! I've made the changes you've requested (hoping I've done them correctly).

As for your first question, I am only looking to leverage these fields in the staging models of my own project.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for the clarification @phillem15! I will plan to give your changes a final review and possibly merge later this week 😄 

I will let you know if I have any other questions!

**Comment by phillem15** [comment]
Hi @fivetran-joemarkiewicz I realized the tests I conducted were not looking at my official changes. I have retested and made some final adjustments to the models. I have re-run the tests and everything is now looking good on my end. Thanks!

**Review by fivetran-joemarkiewicz — APPROVED** [review]
@phillem15 thanks so much for this contribution 😄 

I made one small edit to your branch to increase the version of the package to the next appropriate index. Aside from that, I tested on our own Netsuite data and saw the passthrough columns work as intended and also had no downstream impacts. Looks great to me!

We are extremely appreciative of your contribution to one of our packages and I happy you are able to leverage it in your own environment! I will merge these changes and cut a release shortly!

**Pull request merged**
