### PR TITLE
feature/account-eliminate-field-add

### PR DESCRIPTION
**Pull request by fivetran-joemarkiewicz**
## PR Overview
**This PR will address the following Issue/Feature:** [dbt_netstuite Issue #87](https://github.com/fivetran/dbt_netsuite/issues/87)

**This PR will result in the following new package version:** `v0.8.0`

This will result in a breaking change because if users are leveraging the `accounts_pass_through_columns` variable and passing through the `eliminate` field then it will fail due to a duplicate column unexpectedly. Therefore, we should make this a breaking change to account for these users.

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

This PR includes the addition of the `eliminate` field within the `stg_netsuite2__accounts` model. This new field is necessary to properly categories inter-company accounts in downstream calculations.

### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [X] dbt compile
- [X] dbt run –full-refresh
- [X] dbt run
- [X] dbt test
- [n/a] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [X] The appropriate issue has been linked and tagged
- [X] You are assigned to the corresponding issue and this PR
- [x] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [x] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [x] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [X] You have provided details below around the validation steps performed to gain confidence in these changes.

I was able to confirm the `eliminate` field was being pulled through to the `stg_netsuite__accounts` model as `is_eliminate` and was showing as a boolean that may be leveraged in downstream transformations.

image

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [X] indexed within dbt_project.yml
    - [X] indexed within integration_tests/dbt_project.yml
- [X] CHANGELOG has individual entries for each respective change in this PR
    
- [X] README updates have been applied (if applicable)
    
- [n/a] DECISIONLOG updates have been updated (if applicable)
- [x] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [x] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
🏎️

### CODE REVIEW

**Comment by fivetran-catfritz** [comment]
@fivetran-joemarkiewicz I had one question before I finish up, would it make sense to add the netsuite column `is_included_in_elimination` while we're making netsuite2 updates? I don't think it necessarily needs to be pulled into the transform, but I was wondering if we want to include it if we ever need it?

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-catfritz good question, we have recently only been supporting Nestuite2 in updates but I feel it would be worthwhile to sync as a team and align on if we should continue to support Netsuite1. For the time being I will keep it excluded from the staging model as it is not essential in the downstream logic for Netsuite1. However, we can reconsider this following further discussions tomorrow.

**Review by fivetran-catfritz — APPROVED** [review]
Ran and tested locally. Verified output brings in `eliminate` to tmp and assigns correct boolean to `is_eliminate`! 

(Also just a note--might need to add that temp fix to requirements.txt to get it to pass buildkite when merging into main.)

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-catfritz I just merged in and made some additional changes from PR #40 so they may be incorporated alongside these updates. Would you be able to give another review on these additions? If all looks good I will move forward with the release process.

**Review by fivetran-catfritz — APPROVED** [review]
@fivetran-joemarkiewicz It all lgtm!

**Pull request merged**
